"building_menus"
{
	"basic_building_menu"
	{
		"1" "build_petri_tent"
		"2" "build_petri_sawmill"
		"3" "build_petri_tower_basic"
		"4" "build_petri_wall"
		"5" "petri_empty2"
		"6" "petri_close_basic_buildings_menu"
	}

	"advanced_building_menu"
	{
		"1" "build_petri_gold_tower"
		"2" "build_petri_lab"
		"3" "build_petri_idol"
		"4" "build_petri_exploration_tree"
		"5" "build_petri_exit"
		"6" "petri_close_advanced_buildings_menu"
	}
}