// 41110316 - 78
// 99924802 - alik
// 121983485 - Ane4ka
// 148885092 - Kitayynka
// 161711629 - toporAlexander
// 26966141 - owner-089 IvanDonater
// 149414737 - villanuevavien5 GUlya Venga petri
// 177350248 - solis77 Banned
// 62722684 - abuse.boy500lvl
// 137299635 = error404 LOH EBANIY V BAN SUKU
// 90046454 - greenkzn
// 143426941 - nandakyaway Lin Aung n/a
// 145130295 - errorFAKE LOH EBANIY V BAN SUKU
// 303080098 - errorFAKE2 LOH EBANIY V BAN SUKU
// 303672193 - dnkosiri 2(zamena
// 301902633 - doter14 Doter Romanov
// 87830991 - Potnaya Popka 131215
// 295472945 - 4elizVK 171215
// 170425948 - kir23072 241215
// 171781949 - alukard-Gilgamesh 241215-2mesyca
// 118887766 - tit-mouse 241215-2mesyca
// 168128896 - Moose 241215-2mesyca
// 85977312 - stacy96la Nastya LA 271215
// 129156348 - cristal_de_neigeILITACHVERA noviygod
// 113916753 - Zohan
// 224175813 - VK Anton Kim noviygod
// 120578788 - Dыnьka 240116

"custom_buildings"
{
	"default"
	{
		"npc_petri_tower_basic"
		{
			"models/props_structures/wooden_sentry_tower001.vmdl" "model"
		}
		"npc_petri_wall" 
		{
			"models/props_debris/merchant_debris_chest002.vmdl" "model"
		}
		"npc_petri_earth_wall"
		{
			"models/items/earth_spirit/demon_stone_summon/demon_stone_summon.vmdl" "model"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.35"									 "scale"
		}
		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_barracks001_ranged.vmdl" "model"
			"0.5"									 "scale"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/good_barracks_ranged002_lvl2.vmdl" "model"
			"0.7"									 "scale"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/good_ancient001.vmdl" "model"
			"0.5"									 "scale"
		}
		"npc_petri_sawmill_4"	
		{
			"models/props_structures/radiant_ancient001.vmdl" "model"
			"models/items/bounty_hunter/bounty_hunter_blade.vmdl" "attach_origin"
			"models/items/shredder/timberthaw_offhand/timberthaw_offhand.vmdl" "attach_origin"
			"models/items/shredder/sctimberoffhand/sctimberoffhand.vmdl" "attach_origin"
			"models/items/bounty_hunter/immortal_warrior_shuriken/immortal_warrior_shuriken.vmdl" "attach_origin"
			"models/items/bounty_hunter/hunternoname_shoulder/hunternoname_shoulder.vmdl" "attach_origin"
			"0.5"									 "scale"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.45"									 "scale"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.5"									 "scale"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.55"									 "scale"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.6"									 "scale"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.65"									 "scale"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.7"									 "scale"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.75"									 "scale"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/radiant_tower001.vmdl" "model"
			"0.8"									 "scale"
		}
	}
	"161711629"
	{
		"npc_petri_exit" "models/props_structures/bad_ancient002.vmdl"
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/stonebound_ward/stonebound_ward.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/invoker/forge_spirit/dark_sorcerer_forge_spirit/dark_sorcerer_forge_spirit.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/nexon_turtle_17_gold/nexon_turtle_17_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/faceless_rex/faceless_rex.vmdl" "model"
			"1.9"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.28"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.33"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.38"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.43"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.48"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.53"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.58"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.63"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/bad_tower_destruction.vmdl" "model"
			"0.68"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_c/n_creep_satyr_c.vmdl"
		"npc_petri_super_peasant" "models/heroes/life_stealer/life_stealer.vmdl"

		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_barracks001_destruction.vmdl" "model"
			"0.37"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/bad_barracks001_destruction.vmdl" "model"
			"0.47"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/bad_barracks001_destruction.vmdl" "model"
			"0.57"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/coffin002.vmdl" "model"
			"0.5"									 "scale"
			"180"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/coffin002.vmdl" "model"
   			"0.6"									 "scale"
   			"180"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/coffin002.vmdl" "model"
			"0.7"									 "scale"
			"180"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/coffin002.vmdl" "model"
			"0.8"									 "scale"
			"180"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/warlock/warlock.vmdl" "model"
			"models/items/warlock/archivist_shoulders/archivist_shoulders.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_head/archivist_head.vmdl" "attach_hitloc"
			"models/items/warlock/archivists_robe/archivists_robe.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_facebag/archivist_facebag.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_lantern/archivist_lantern.vmdl" "attach_attack2"
			"models/items/warlock/ceaseless/ceaseless.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/lich/lich.vmdl" "model"
			"models/items/lich/imperialists_frost_biter/imperialists_frost_biter.vmdl" "attach_portrait"
			"models/items/lich/the_deadwinter_head/the_deadwinter_head.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_legfrost"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"143426941"
	{
		"npc_petri_exit" 
		{
		"models/props_structures/secretshop_asian001.vmdl" "model"
			"1.02"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/techies/bigshot/bigshot_remotebomb.vmdl" "model"
			"1"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/chinese_ward/chinese_ward.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/courier/greevil/gold_greevil.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/blotto_and_stick/blotto.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.79"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.87"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.95"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.05"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.15"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.25"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.35"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.45"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.55"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_super_peasant" 
		{
			"models/heroes/rikimaru/rikimaru.vmdl" "model"
			"models/heroes/troll_warlord/troll_warlord_axe_melee_r.vmdl" "attach_attack1"
			"models/items/axe/skullsplitter/skullsplitter.vmdl" "attach_attack2"
			"models/items/shredder/top_hat_of_the_steam_chopper/top_hat_of_the_steam_chopper.vmdl" "attach_hitloc"
			"models/props_gameplay/halloween_candy.vmdl" "attach_hitloc"
			"1.32"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.33"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.43"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.53"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
			"0.7"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
   			"0.9"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.67"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/witchdoctor/witchdoctor.vmdl" "model"
			"models/items/witchdoctor/baron_la_croix_staff/baron_la_croix_staff.vmdl" "attach_staff"
			"models/items/witchdoctor/purplenightmare_belt/purplenightmare_belt.vmdl" "attach_hitloc"
			"models/items/witchdoctor/pet_snake.vmdl" "attach_hitloc"
			"1.45"									 "scale"
		}

		"npc_petri_tower_basic_cold" 	"models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"171781949"
	{
		"npc_petri_exit" 
		{
		"models/props_structures/secretshop_asian001.vmdl" "model"
			"1.02"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/techies/bigshot/bigshot_remotebomb.vmdl" "model"
			"1"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/chinese_ward/chinese_ward.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/courier/greevil/gold_greevil.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/blotto_and_stick/blotto.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.79"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.87"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"0.95"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.05"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.15"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.25"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.35"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.45"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_debris/chinese_lantern002.vmdl" "model"
			"1.55"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_super_peasant" 
		{
			"models/heroes/rikimaru/rikimaru.vmdl" "model"
			"models/heroes/troll_warlord/troll_warlord_axe_melee_r.vmdl" "attach_attack1"
			"models/items/axe/skullsplitter/skullsplitter.vmdl" "attach_attack2"
			"models/items/shredder/top_hat_of_the_steam_chopper/top_hat_of_the_steam_chopper.vmdl" "attach_hitloc"
			"models/props_gameplay/halloween_candy.vmdl" "attach_hitloc"
			"1.32"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.33"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.43"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.53"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
			"0.7"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
   			"0.9"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.67"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/witchdoctor/witchdoctor.vmdl" "model"
			"models/items/witchdoctor/baron_la_croix_staff/baron_la_croix_staff.vmdl" "attach_staff"
			"models/items/witchdoctor/purplenightmare_belt/purplenightmare_belt.vmdl" "attach_hitloc"
			"models/items/witchdoctor/pet_snake.vmdl" "attach_hitloc"
			"1.45"									 "scale"
		}

		"npc_petri_tower_basic_cold" 	"models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/particle/snowball.vmdl" "model"
			"models/minigun/minigun.vmdl" "attach_origin"
			"1.6"	"attack_speed"
			"0.4"									 "scale"
		}
	}	
	"177350248"
	{
		"npc_petri_exit" 
		{
		"models/props_structures/secretshop_asian001.vmdl" "model"
			"1.02"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/techies/bigshot/bigshot_remotebomb.vmdl" "model"
			"1"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/chinese_ward/chinese_ward.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/courier/greevil/gold_greevil.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/blotto_and_stick/blotto.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_super_peasant" 
		{
			"models/heroes/rikimaru/rikimaru.vmdl" "model"
			"models/heroes/troll_warlord/troll_warlord_axe_melee_r.vmdl" "attach_attack1"
			"models/items/axe/skullsplitter/skullsplitter.vmdl" "attach_attack2"
			"models/items/shredder/top_hat_of_the_steam_chopper/top_hat_of_the_steam_chopper.vmdl" "attach_hitloc"
			"models/props_gameplay/halloween_candy.vmdl" "attach_hitloc"
			"1.32"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.33"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.43"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.53"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
			"0.7"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/dragon_statue001.vmdl" "model"
   			"0.9"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.67"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/witchdoctor/witchdoctor.vmdl" "model"
			"models/items/witchdoctor/baron_la_croix_staff/baron_la_croix_staff.vmdl" "attach_staff"
			"models/items/witchdoctor/purplenightmare_belt/purplenightmare_belt.vmdl" "attach_hitloc"
			"models/items/witchdoctor/pet_snake.vmdl" "attach_hitloc"
			"1.45"									 "scale"
		}

		"npc_petri_tower_basic_cold" 	"models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"90046454"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_ward_of_foresight/esl_wardchest_ward_of_foresight.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/lone_druid/true_form/wizened_bear/wizened_bear.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/witchdoctor/wd_ward/ribbitar_ward/ribbitar_ward.vmdl" "model"
			"25	"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
   			"1.33"									 "scale"
   			"250"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1.66"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"2"									 "scale"
			"250"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/tuskarr/whiskey_the_stout/whiskey_the_stout_slider.vmdl" "model"
			"4"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/coco_the_courageous/coco_the_courageous.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"	"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/items/lone_druid/true_form/rabid_black_bear/rabid_black_bear.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"120578788"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/frozen_formation/frozen_formation.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire"
		{
			"models/heroes/lina/lina.vmdl" "model"
			"models/items/lanaya/exotic_assassin_curls/exotic_assassin_curls.vmdl" "attach_head"
			"1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_bag" 
		{
			"models/items/courier/snowl/snowl.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/tory_the_sky_guardian/tory_the_sky_guardian.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_vulture_b/n_creep_vulture_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
   			"1.2"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.6"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/courier/bearzky_v2/bearzky_v2.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/scuttling_scotty_penguin/scuttling_scotty_penguin.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}
		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"170425948"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_ward_of_foresight/esl_wardchest_ward_of_foresight.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/lone_druid/true_form/wizened_bear/wizened_bear.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/witchdoctor/wd_ward/ribbitar_ward/ribbitar_ward.vmdl" "model"
			"25	"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
   			"1.33"									 "scale"
   			"250"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1.66"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"2"									 "scale"
			"250"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/tuskarr/whiskey_the_stout/whiskey_the_stout_slider.vmdl" "model"
			"4"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/coco_the_courageous/coco_the_courageous.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"	"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/items/lone_druid/true_form/rabid_black_bear/rabid_black_bear.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"26966141zz"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_ward_of_foresight/esl_wardchest_ward_of_foresight.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/lone_druid/true_form/wizened_bear/wizened_bear.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/faceless_rex/faceless_rex_flying.vmdl" "model"
			"25"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
   			"1.33"									 "scale"
   			"250"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1.66"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"2"									 "scale"
			"250"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/tuskarr/whiskey_the_stout/whiskey_the_stout_slider.vmdl" "model"
			"4"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/coco_the_courageous/coco_the_courageous.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"	"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"99924802zzzz"
	{
		"npc_petri_exit"
		{
			"models/props_cave/wooden_ladder_256.vmdl" "model"
			"2.4"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/heroes/techies/techies_bomb_projectile.vmdl" "model"
			"4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/ocula/ocula.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/invoker/forge_spirit/dark_sorcerer_forge_spirit/dark_sorcerer_forge_spirit.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/hex/sheep_hex/sheep_hex_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/arneyb_rabbit/arneyb_rabbit.vmdl" "model"
			"1.9"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.16"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.18"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.20"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.21"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.23"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.25"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.26"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.28"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.30"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_c/n_creep_satyr_c.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/heroes/rikimaru/rikimaru.vmdl" "model"
			"models/heroes/troll_warlord/troll_warlord_axe_melee_r.vmdl" "attach_attack1"
			"models/items/axe/skullsplitter/skullsplitter.vmdl" "attach_attack2"
			"models/items/shredder/top_hat_of_the_steam_chopper/top_hat_of_the_steam_chopper.vmdl" "attach_hitloc"
			"models/props_gameplay/halloween_candy.vmdl" "attach_hitloc"
			"1.32"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/factory/factory.vmdl" "model"
			"0.05"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/factory/factory.vmdl" "model"
			"0.06"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/factory/factory.vmdl" "model"
			"0.07"									 "scale"
			"0"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/yurta/yurta.vmdl" "model"
			"0.45"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/yurta2/yurta_2.vmdl" "model"
   			"0.6"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/yurta3/yurta_3.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/yurta4/yurta_4.vmdl" "model"
			"0.90"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/warlock/warlock.vmdl" "model"
			"models/items/warlock/archivist_shoulders/archivist_shoulders.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_head/archivist_head.vmdl" "attach_hitloc"
			"models/items/warlock/archivists_robe/archivists_robe.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_facebag/archivist_facebag.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_lantern/archivist_lantern.vmdl" "attach_attack2"
			"models/items/warlock/ceaseless/ceaseless.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/lich/lich.vmdl" "model"
			"models/items/lich/imperialists_frost_biter/imperialists_frost_biter.vmdl" "attach_portrait"
			"models/items/lich/the_deadwinter_head/the_deadwinter_head.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_legfrost"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/particle/snowball.vmdl" "model"
			"models/minigun/minigun.vmdl" "attach_origin"
			"1.6"	"attack_speed"
			"0.4"									 "scale"
		}
	}	
	"301902633"
	{
		"npc_petri_exit"
		{
			"models/props_structures/ship_broken001.vmdl" "model"
			"0.4"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/furion/dark_staff/bulb.vmdl" "model"
			"0.28"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_rockshell_terrapin/esl_wardchest_rockshell_terrapin.vmdl" "model"
			"2.3"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tower_basic_fire"
		{
			"models/heroes/lina/lina.vmdl" "model"
			"models/items/lanaya/exotic_assassin_curls/exotic_assassin_curls.vmdl" "attach_head"
			"1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_bag" 
		{
			"models/courier/baby_rosh/babyroshan.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/furion/treant_flower_1.vmdl" "model"
			"1.2"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_doubledamage01.vmdl" "model"
			"2.0"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	"models/items/furion/treant_stump.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/items/furion/treant/fungal_lord_shroomthing/fungal_lord_shroomthing.vmdl" "model"
			"0.99"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_gameplay/rune_haste01.vmdl" "model"
			"1.5"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_gameplay/rune_haste01.vmdl" "model"
			"1.85"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_gameplay/rune_haste01.vmdl" "model"
			"2.3"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_gameplay/rune_illusion01.vmdl" "model"
			"1"									 "scale"
			"180"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_gameplay/rune_illusion01.vmdl" "model"
   			"1.2"									 "scale"
   			"180"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_gameplay/rune_illusion01.vmdl" "model"
			"1.4"									 "scale"
			"180"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_gameplay/rune_illusion01.vmdl" "model"
			"1.6"									 "scale"
			"180"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/alchemist/alchemist.vmdl" "model"
			"models/items/omniknight/weapon_rune_hammer.vmdl" "attach_attack1"
			"models/items/rattletrap/ironclock_weapon/ironclock_weapon.vmdl" "attach_attack2"
			"models/heroes/alchemist/alchemist_ogre_head.vmdl" "attach_ogerhead"
			"models/heroes/alchemist/alchemist_saddlehat.vmdl" "attach_hitloc"
			"models/items/sniper/machine_gun_charlie/machine_gun_charlie.vmdl" "attach_hitloc"
		}

		"npc_petri_idol" 
		{
			"models/heroes/axe/axe.vmdl" "model"
			"models/items/keeper_of_the_light/strikeofthelight_weapon/strikeofthelight_weapon.vmdl" "attach_weapon"
			"models/items/sniper/gunslinger_head/gunslinger_headitem.vmdl" "attach_mouth"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/items/furion/treant/primeval_treant/primeval_treant.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/furion/treant/primeval_treant/primeval_treant.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1.01"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/furion/treant/primeval_treant/primeval_treant.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1.21"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/furion/treant/primeval_treant/primeval_treant.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1.42"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}
	"148885092"
	{
		"npc_petri_exit"
		{
			"models/heroes/phantom_assassin/arcana_tombstone.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/chinese_ward/chinese_ward.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/itsy/itsy.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/shroomy/shroomy.vmdl" "model"
			"1.9"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"
		{
			"models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_super_peasant"
		{
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
			"0.7"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1.25"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1.48"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
   			"1.2"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.6"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/items/courier/bookwyrm/bookwyrm.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}

		"npc_petri_idol" 
		{
			"models/items/courier/dc_demon/dc_demon.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/puck/puck.vmdl" "model"
			"models/items/puck/mischievousfruits_head/mischievousfruits_head.vmdl" "attach_hitloc"
			"models/items/puck/merry_wanderers_brush_tail/merry_wanderers_brush_tail.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_hitloc"
		}

		"npc_petri_tower_of_evil"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.2"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.4"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.6"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/creeps/item_creeps/i_creep_necro_archer/necro_archer.vmdl" "model"
		}
	}	
	"85977312"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/frozen_formation/frozen_formation.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/tuskarr/sigil/boreal_sigil/boreal_sigil.vmdl" "model"
			"models/props_gameplay/gold_bag.vmdl" "attach_hitloc"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_pink.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_ruby.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_saphire.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_topaz.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_pink.vmdl" "flame_attachment"
			"0"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/scuttling_scotty_penguin/scuttling_scotty_penguin.vmdl" "model"
			"1.9"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/items/lone_druid/viciouskraitpanda/viciouskrait_panda.vmdl" "model"
			"0.70"									 "scale"
		}
		"npc_petri_super_peasant" 
		{
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.33"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.43"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.53"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
   			"1.2"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.6"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/items/courier/arneyb_rabbit/arneyb_rabbit.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}

		"npc_petri_idol" 
		{
			"models/items/courier/dc_angel/dc_angel.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/particle/snowball.vmdl" "model"
			"models/minigun/minigun.vmdl" "attach_origin"
			"1.6"	"attack_speed"
			"0.4"									 "scale"
		}
	}	
	"99924802zz"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/frozen_formation/frozen_formation.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire"
		{
			"models/heroes/lina/lina.vmdl" "model"
			"models/items/lanaya/exotic_assassin_curls/exotic_assassin_curls.vmdl" "attach_head"
			"1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_bag" 
		{
			"models/items/courier/snowl/snowl.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/tory_the_sky_guardian/tory_the_sky_guardian.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_vulture_b/n_creep_vulture_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/units/ironman/ironman.vmdl" "model"
			"60"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
   			"1.2"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.6"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/courier/bearzky_v2/bearzky_v2.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/scuttling_scotty_penguin/scuttling_scotty_penguin.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"
		{
			"models/heroes/lich/lich.vmdl" "model"
			"models/items/lich/imperialists_frost_biter/imperialists_frost_biter.vmdl" "attach_portrait"
			"models/items/lich/the_deadwinter_head/the_deadwinter_head.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_legfrost"
		}
		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"26966141"
	{
		"npc_petri_exit"
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/christmas_tree/christmas_tree.vmdl" "attach_origin"
			"1.0"							 "scale"
			"0"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/crystal_maiden/ward_staff/ward_staff_crystal.vmdl" "model"
			"2.8"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/skywrath_sentinel/skywrath_sentinel.vmdl" "model"
			"2.3"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/faceless_rex/faceless_rex_flying.vmdl" "model"
			"25"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_arcane.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_regeneration01.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/bad_barracks001_ranged.vmdl" "attach_origin"
			"0.55"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_barracks_ranged002_lvl2.vmdl" "attach_origin"
			"0.6"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_ancient001.vmdl" "attach_origin"
			"0.65"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_4"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/radiant_ancient001.vmdl" "attach_origin"
			"models/items/bounty_hunter/bounty_hunter_blade.vmdl" "attach_origin"
			"models/items/shredder/timberthaw_offhand/timberthaw_offhand.vmdl" "attach_origin"
			"models/items/shredder/sctimberoffhand/sctimberoffhand.vmdl" "attach_origin"
			"models/items/bounty_hunter/immortal_warrior_shuriken/immortal_warrior_shuriken.vmdl" "attach_origin"
			"models/items/bounty_hunter/hunternoname_shoulder/hunternoname_shoulder.vmdl" "attach_origin"
			"0.7"									 "scale"
			"0"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
   			"1.2"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/courier/bts_chirpy/bts_chirpy.vmdl" "model"
			"1.6"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/items/courier/bookwyrm/bookwyrm.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/dc_demon/dc_demon.vmdl" "model"
			"2"									 "scale"
			"225"									"yaw"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.15"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.17"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.19"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.21"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}
	"224175813"
	{
		"npc_petri_exit"
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/christmas_tree/christmas_tree.vmdl" "attach_origin"
			"1.0"							 "scale"
			"0"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/crystal_maiden/ward_staff/ward_staff_crystal.vmdl" "model"
			"2.8"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/crystal_maiden_ward/crystal_maiden_ward.vmdl" "model"
			"2.3"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/faceless_rex/faceless_rex_flying.vmdl" "model"
			"25"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.15"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.16"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.17"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.18"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.19"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.20"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.21"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.22"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/gold_tower_4/gold_tower_4.vmdl" "model"
			"0.23"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/items/lone_druid/viciouskraitpanda/viciouskrait_panda.vmdl" "model"
			"0.70"									 "scale"
		}
		"npc_petri_super_peasant" 
		{
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/bad_barracks001_ranged.vmdl" "attach_origin"
			"0.55"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_barracks_ranged002_lvl2.vmdl" "attach_origin"
			"0.6"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_ancient001.vmdl" "attach_origin"
			"0.65"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_4"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/radiant_ancient001.vmdl" "attach_origin"
			"models/items/bounty_hunter/bounty_hunter_blade.vmdl" "attach_origin"
			"models/items/shredder/timberthaw_offhand/timberthaw_offhand.vmdl" "attach_origin"
			"models/items/shredder/sctimberoffhand/sctimberoffhand.vmdl" "attach_origin"
			"models/items/bounty_hunter/immortal_warrior_shuriken/immortal_warrior_shuriken.vmdl" "attach_origin"
			"models/items/bounty_hunter/hunternoname_shoulder/hunternoname_shoulder.vmdl" "attach_origin"
			"0.7"									 "scale"
			"0"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/yurta/yurta.vmdl" "model"
			"0.45"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/yurta2/yurta_2.vmdl" "model"
   			"0.6"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/yurta3/yurta_3.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/yurta4/yurta_4.vmdl" "model"
			"0.90"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/snowman/snowman.vmdl" "attach_origin"
			"models/lolipop/lollipop.vmdl" "attach_origin"
			"models/items/omniknight/hammerofenlight/hammerofenlight.vmdl" "attach_origin"
		}

		"npc_petri_idol" 
		{
			"models/items/courier/basim/basim.vmdl" "model"
			"1.75"									 "scale"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_death"
		{
			"models/particle/snowball.vmdl" "model"
			"models/minigun/minigun.vmdl" "attach_origin"
			"1.6"	"attack_speed"
			"0.4"									 "scale"
		}
	}
	"129156348"
	{
		"npc_petri_exit"
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/christmas_tree/christmas_tree.vmdl" "attach_origin"
			"1.0"							 "scale"
			"0"									"yaw"
		}
		"npc_petri_trap"
		{
			"models/items/crystal_maiden/ward_staff/ward_staff_crystal.vmdl" "model"
			"2.8"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/crystal_maiden_ward/crystal_maiden_ward.vmdl" "model"
			"2.3"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/tuskarr/sigil/boreal_sigil/boreal_sigil.vmdl" "model"
			"models/props_gameplay/gold_bag.vmdl" "attach_hitloc"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_pink.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_ruby.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_saphire.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_topaz.vmdl" "flame_attachment"
			"models/items/meepo/diggers_divining_rod/diggers_divining_rod_gem_pink.vmdl" "flame_attachment"
			"0"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/arneyb_rabbit/arneyb_rabbit.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.15"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.16"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/gold_tower/gold_tower.vmdl" "model"
			"0.17"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.18"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.19"									 "scale"
			"45"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/gold_tower_2/gold_tower_2.vmdl" "model"
			"0.20"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.21"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/gold_tower_3/gold_tower_3.vmdl" "model"
			"0.22"									 "scale"
			"315"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/gold_tower_4/gold_tower_4.vmdl" "model"
			"0.23"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/items/lone_druid/viciouskraitpanda/viciouskrait_panda.vmdl" "model"
			"0.70"									 "scale"
		}
		"npc_petri_super_peasant" 
		{
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
			"0.6"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/bad_barracks001_ranged.vmdl" "attach_origin"
			"0.55"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_barracks_ranged002_lvl2.vmdl" "attach_origin"
			"0.6"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/good_ancient001.vmdl" "attach_origin"
			"0.65"									 "scale"
			"0"									"yaw"
		}
		"npc_petri_sawmill_4"	
		{
			"models/factory/factory.vmdl" "model"
			"models/props_structures/radiant_ancient001.vmdl" "attach_origin"
			"models/items/bounty_hunter/bounty_hunter_blade.vmdl" "attach_origin"
			"models/items/shredder/timberthaw_offhand/timberthaw_offhand.vmdl" "attach_origin"
			"models/items/shredder/sctimberoffhand/sctimberoffhand.vmdl" "attach_origin"
			"models/items/bounty_hunter/immortal_warrior_shuriken/immortal_warrior_shuriken.vmdl" "attach_origin"
			"models/items/bounty_hunter/hunternoname_shoulder/hunternoname_shoulder.vmdl" "attach_origin"
			"0.7"									 "scale"
			"0"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/yurta/yurta.vmdl" "model"
			"0.45"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/yurta2/yurta_2.vmdl" "model"
   			"0.6"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/yurta3/yurta_3.vmdl" "model"
			"0.75"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/yurta4/yurta_4.vmdl" "model"
			"0.90"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/snowman/snowman.vmdl" "attach_origin"
			"models/lolipop/lollipop.vmdl" "attach_origin"
			"models/items/omniknight/hammerofenlight/hammerofenlight.vmdl" "attach_origin"
		}

		"npc_petri_idol" 
		{
			"models/items/courier/basim/basim.vmdl" "model"
			"1.75"									 "scale"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.15"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.17"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.19"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/xyu/xyu.vmdl" "model"

			"1.6"	"attack_speed"
			"180"	"yaw"
			"0.21"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/particle/snowball.vmdl" "model"
			"models/minigun/minigun.vmdl" "attach_origin"
			"1.6"	"attack_speed"
			"0.4"									 "scale"
		}
	}
	"303672193"
	{
		"npc_petri_exit"
		{
			"models/heroes/kunkka/ghostship_sim.vmdl" "model"
			"2.0"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_toadstool/esl_wardchest_toadstool.vmdl" "model"
			"2.2"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire"
		{
			"models/heroes/slardar/slardar.vmdl" "model"
			"models/heroes/slardar/slardar_head.vmdl" "attach_light"
			"models/items/warlock/tevent_2_gatekeeper_scythe/tevent_2_gatekeeper_scythe.vmdl" "attach_attack1"
			"0.99 "									 "scale"
		}
		"npc_petri_gold_bag" 
		{
			"models/courier/flopjaw/flopjaw.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/courier/smeevil_crab/smeevil_crab.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/items/courier/coral_furryfish/coral_furryfish.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	
		{
			"models/heroes/venomancer/venomancer.vmdl" "model"
			"1.15"									 "scale"
		}

		"npc_petri_super_peasant" 
		{
			"models/heroes/tidehunter/tidehunter.vmdl" "model"
			"0.99"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/props_structures/crystal002.vmdl" "attach_origin"
			"0.75"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/props_structures/crystal002.vmdl" "attach_origin"
			"0.87"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/heroes/crystal_maiden/pedestal_cm_arcana.vmdl" "model"
			"models/props_structures/crystal002.vmdl" "attach_origin"
			"0.99"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/radiant_statue001.vmdl" "model"
			"0.45"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/radiant_statue001.vmdl" "model"
   			"0.55"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/radiant_statue001.vmdl" "model"
			"0.65"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/radiant_statue001.vmdl" "model"
			"0.75	"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/items/courier/g1_courier/g1_courier.vmdl" "model"
			"1.75"									 "scale"
		}

		"npc_petri_idol" 
		{
			"models/items/courier/itsy/itsy.vmdl" "model"
			"1.75"									 "scale"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/morphling/morphling.vmdl" "model"
			"1.15"									 "scale"
		}

		"npc_petri_tower_of_evil"
		{
			"models/courier/venoling/venoling.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1.99"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/courier/venoling/venoling.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.3"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/courier/venoling/venoling.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.6"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/courier/venoling/venoling.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.99"	"scale"
		}
		"npc_petri_tower_basic_death"
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/heroes/tidehunter/tidehuntertentacle.vmdl" "attach_origin"
			"0.75"									 "scale"
			"270"									"yaw"
		}
	}	
	"149414737"
	{
		"npc_petri_exit" "models/props_structures/bad_ancient002.vmdl"
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/dire_ward_eye/dire_ward_eye.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/nexon_turtle_17_gold/nexon_turtle_17_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/vaal_the_animated_constructradiant/vaal_the_animated_constructradiant_flying.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
		"models/heroes/shadow_demon/shadow_demon.vmdl" "model"
		"models/heroes/shadow_demon/shadow_demon_cape.vmdl" "attach_hitloc"
		"models/heroes/shadow_demon/shadow_demon_chain.vmdl" "attach_hitloc"
		}

		"npc_petri_super_peasant" 
		{
			"models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl" "model"
			"0.75"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.26"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.29"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.32"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.18"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/cathedral001.vmdl" "model"
   			"0.23"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.28"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.35"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/warlock/warlock.vmdl" "model"
			"models/items/warlock/archivist_shoulders/archivist_shoulders.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_head/archivist_head.vmdl" "attach_hitloc"
			"models/items/warlock/archivists_robe/archivists_robe.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_facebag/archivist_facebag.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_lantern/archivist_lantern.vmdl" "attach_attack2"
			"models/items/warlock/ceaseless/ceaseless.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}
		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"118887766"
	{
		"npc_petri_exit"
		{
			"models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl" "model"
			"3.5"									 "scale"
		}
		"npc_petri_trap"
		{
			"models/particle/snowball.vmdl" "model"
			"0.4"									 "scale"
		}
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/esl_wardchest_ward_of_foresight/esl_wardchest_ward_of_foresight.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/items/lone_druid/true_form/wizened_bear/wizened_bear.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/witchdoctor/wd_ward/ribbitar_ward/ribbitar_ward.vmdl" "model"
			"25	"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl" "model"
			"1.8"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_peasant"	"models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"npc_petri_super_peasant" 
		{
			"models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.30"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.38"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/kings_chair.vmdl" "model"
			"0.47"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
   			"1.33"									 "scale"
   			"250"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"1.66"									 "scale"
			"250"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/items/tuskarr/sigil/barrierrogue_tusk_sigil/barrierrogue_tusk_sigil.vmdl" "model"
			"2"									 "scale"
			"250"									"yaw"
		}

		"npc_petri_lab" 	
		{
			"models/items/tuskarr/whiskey_the_stout/whiskey_the_stout_slider.vmdl" "model"
			"4"									 "scale"
		}
		"npc_petri_idol" 
		{
			"models/items/courier/coco_the_courageous/coco_the_courageous.vmdl" "model"
			"2"									 "scale"
		}
		"npc_petri_tower_basic_cold"	"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl"
		"npc_petri_tower_of_evil"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/items/lone_druid/true_form/rabid_black_bear/rabid_black_bear.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"168128896"
	{
		"npc_petri_exit" "models/props_structures/bad_ancient002.vmdl"
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/dire_ward_eye/dire_ward_eye.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/nexon_turtle_17_gold/nexon_turtle_17_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/vaal_the_animated_constructradiant/vaal_the_animated_constructradiant_flying.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
		"models/heroes/shadow_demon/shadow_demon.vmdl" "model"
		"models/heroes/shadow_demon/shadow_demon_cape.vmdl" "attach_hitloc"
		"models/heroes/shadow_demon/shadow_demon_chain.vmdl" "attach_hitloc"
		}

		"npc_petri_super_peasant" 
		{
			"models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl" "model"
			"0.75"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.26"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.29"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.32"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.18"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/cathedral001.vmdl" "model"
   			"0.23"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.28"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.35"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/warlock/warlock.vmdl" "model"
			"models/items/warlock/archivist_shoulders/archivist_shoulders.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_head/archivist_head.vmdl" "attach_hitloc"
			"models/items/warlock/archivists_robe/archivists_robe.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_facebag/archivist_facebag.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_lantern/archivist_lantern.vmdl" "attach_attack2"
			"models/items/warlock/ceaseless/ceaseless.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}
		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"295472945"
	{
		"npc_petri_exit" "models/props_structures/bad_ancient002.vmdl"
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/dire_ward_eye/dire_ward_eye.vmdl" "model"
			"2.4"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/courier/nexon_turtle_17_gold/nexon_turtle_17_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/vaal_the_animated_constructradiant/vaal_the_animated_constructradiant_flying.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
		"models/heroes/shadow_demon/shadow_demon.vmdl" "model"
		"models/heroes/shadow_demon/shadow_demon_cape.vmdl" "attach_hitloc"
		"models/heroes/shadow_demon/shadow_demon_chain.vmdl" "attach_hitloc"
		}

		"npc_petri_super_peasant" 
		{
			"models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl" "model"
			"0.75"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.26"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.29"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.32"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.18"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/cathedral001.vmdl" "model"
   			"0.23"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.28"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.35"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/heroes/pudge/pudge.vmdl" "model"
			"models/items/pudge/ftp_dendi_shoulder/ftp_dendi_shoulder.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_head/ftp_dendi_head.vmdl" "attach_eye_l"
			"models/items/pudge/ftp_dendi_arm/ftp_dendi_arm.vmdl" "attach_arm_chain_rt"
			"models/items/pudge/ftp_dendi_back/ftp_dendi_back.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_offhand/ftp_dendi_offhand.vmdl" "attach_hitloc"
			"models/items/pudge/ftp_dendi_weapon/ftp_dendi_weapon.vmdl" "attach_attack1"
		}

		"npc_petri_idol" 
		{
			"models/heroes/warlock/warlock.vmdl" "model"
			"models/items/warlock/archivist_shoulders/archivist_shoulders.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_head/archivist_head.vmdl" "attach_hitloc"
			"models/items/warlock/archivists_robe/archivists_robe.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_facebag/archivist_facebag.vmdl" "attach_hitloc"
			"models/items/warlock/archivist_lantern/archivist_lantern.vmdl" "attach_attack2"
			"models/items/warlock/ceaseless/ceaseless.vmdl" "attach_attack1"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/obsidian_destroyer/obsidian_destroyer.vmdl" "model"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_rocks.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_wings.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_head.vmdl" "attach_hitloc"
			"models/heroes/obsidian_destroyer/obsidian_destroyer_horns.vmdl" "attach_hitloc"
			"models/items/obsidian_destroyer/immortal_weapon_1/immortal_weapon_1.vmdl" "attach_attack1"

			"1.7"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}
		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}
	}	
	"62722684"
	{
		"npc_petri_exit" "models/props_structures/bad_ancient002.vmdl"
		"npc_petri_trap" "models/items/techies/bigshot/fx_bigshot_stasis.vmdl"
		"npc_petri_exploration_tree" 
		{
			"models/items/wards/knightstatue_ward/knightstatue_ward.vmdl" "model"
			"2"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_gold_bag" 
		{
			"models/items/hex/sheep_hex/sheep_hex_gold.vmdl" "model"
			"270"									"yaw"
		}
		"npc_dota_courier" "models/items/courier/g1_courier/g1_courier_flying.vmdl"
		"npc_petri_cop" 
		{
			"models/items/courier/baekho/baekho.vmdl" "model"
			"1.77"									 "scale"
		}
		"npc_petri_gold_tower" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.35"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.45"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.55"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.65"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.7"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/heroes/pedestal/effigy_pedestal_ti5.vmdl" "model"
			"models/props_structures/gryphon_statue001.vmdl" "attach_origin"
			"0.75"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_peasant"	
		{
		"models/heroes/shadow_demon/shadow_demon.vmdl" "model"
		"models/heroes/shadow_demon/shadow_demon_cape.vmdl" "attach_hitloc"
		"models/heroes/shadow_demon/shadow_demon_chain.vmdl" "attach_hitloc"
		}

		"npc_petri_super_peasant" 
		{
			"models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl" "model"
			"0.75"									 "scale"
		}

		"npc_petri_sawmill"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.26"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.29"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/props_structures/bad_ancient_destruction.vmdl" "model"
			"0.32"									 "scale"
			"90"									"yaw"
		}

		"npc_petri_tent"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.18"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_2"
		{
			"models/props_structures/cathedral001.vmdl" "model"
   			"0.23"									 "scale"
   			"270"									"yaw"
		}
		"npc_petri_tent_3"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.28"									 "scale"
			"270"									"yaw"
		}
		"npc_petri_tent_4"
		{
			"models/props_structures/cathedral001.vmdl" "model"
			"0.35"									 "scale"
			"270"									"yaw"
		}

		"npc_petri_lab" 
		{
			"models/props_structures/statue_dragon001.vmdl" "model"
			"1.3"									 "scale"
		}

		"npc_petri_idol" 
		{
			"models/props_structures/statue_dragon003.vmdl" "model"
			"0.9"									 "scale"
		}

		"npc_petri_tower_basic_cold"
		{
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/items/crystal_maiden/lusciouslocks_head/lusciouslocks_head.vmdl" "attach_head"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "attach_hitloc"
			"models/items/crystal_maiden/northstar_staff/northstar_staff.vmdl" "attach_attack1"
		}

		"npc_petri_tower_of_evil"
		{
			"models/items/shadowshaman/serpent_ward/tangki_serpent_ward/tangki_serpent_ward.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1.99"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/shadowshaman/serpent_ward/tangki_serpent_ward/tangki_serpent_ward.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.3"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/shadowshaman/serpent_ward/tangki_serpent_ward/tangki_serpent_ward.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.6"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/shadowshaman/serpent_ward/tangki_serpent_ward/tangki_serpent_ward.vmdl" "model"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"2.99"	"scale"
		}
		"npc_petri_tower_basic_death"
		{
			"models/creeps/neutral_creeps/n_creep_black_drake/n_creep_black_drake.vmdl" "model"
		}
	}	
	"121983485"
	{
		"npc_petri_tower_basic_fire" "models/items/invoker/forge_spirit/dark_sorcerer_forge_spirit/dark_sorcerer_forge_spirit.vmdl"
		"npc_petri_tower_basic_cold"
		{
			"models/heroes/lich/lich.vmdl" "model"
			"models/items/lich/imperialists_frost_biter/imperialists_frost_biter.vmdl" "attach_portrait"
			"models/items/lich/the_deadwinter_head/the_deadwinter_head.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_legfrost"
		}
		"npc_petri_tower_of_evil"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.8"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.86"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"0.92"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/heroes/necrolyte/necrolyte.vmdl" "model"
			"models/items/necrolyte/heretic_head/heretic_head.vmdl" "attach_head"
			"models/items/necrolyte/heretic_hood/heretic_hood.vmdl" "attach_head"
			"models/items/necrolyte/heretic_shoulder/heretic_shoulder.vmdl" "attach_hitloc"
			"models/items/necrolyte/heretic_weapon/heretic_weapon.vmdl" "attach_attack2"

			"1.6"	"attack_speed"
			"270"	"yaw"
			"1"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/heroes/shadow_fiend/shadow_fiend.vmdl" "model"
			"models/heroes/shadow_fiend/shadow_fiend_head.vmdl" "attach_eyeL"
			"models/items/shadow_fiend/arms_deso/arms_deso.vmdl" "attach_hitloc"
			"models/heroes/shadow_fiend/shadow_fiend_shoulders.vmdl" "attach_hitloc"

			"1.6"	"attack_speed"
			"270"	"yaw"
		}

	}	
	"145130295"
	{
		"npc_petri_gold_tower" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
	}
	"303080098"
	{
		"npc_petri_gold_tower" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
	}
	"137299635"
	{
		"npc_petri_gold_tower" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_structures/gryphon_statue001.vmdl" "model"
			"0.01"									 "scale"
			"225"									"yaw"
		}
	}	
	"113916753"
	{
		"npc_petri_gold_tower" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.1"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.2"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.3"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.4"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.5"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.6"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"1.8"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/props_gameplay/rune_goldxp.vmdl" "model"
			"2.0	"									 "scale"
			"225"									"yaw"
		}
		"npc_petri_gold_bag" 
		{
			"models/courier/baby_rosh/babyroshan.vmdl" "model"
			"270"									"yaw"
		}
	}	
	"87830991"
	{
		"npc_petri_gold_tower" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_2" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.15"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_3" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.27"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_4" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.4"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_5" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.52"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_6" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.64"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_7" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.78"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_8" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"1.9"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_tower_9" 
		{
			"models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl" "model"
			"2.02"									 "scale"
			"248"									"yaw"
		}
		"npc_petri_gold_bag" 
		{
			"models/courier/huntling/huntling.vmdl" "model"
			"270"									"yaw"
		}
		"npc_petri_tower_basic_fire" "models/heroes/phoenix/phoenix_bird.vmdl"
		"npc_petri_sawmill"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_2"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1.25"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_sawmill_3"	
		{
			"models/heroes/techies/techies_cart.vmdl" "model"
			"1.48"									 "scale"
			"90"									"yaw"
		}
		"npc_petri_tower_basic_cold"
		{
			"models/heroes/puck/puck.vmdl" "model"
			"models/items/puck/mischievousfruits_head/mischievousfruits_head.vmdl" "attach_hitloc"
			"models/items/puck/merry_wanderers_brush_tail/merry_wanderers_brush_tail.vmdl" "attach_hitloc"
			"models/items/lich/imperialists_mana_chamber/imperialists_mana_chamber.vmdl" "attach_hitloc"
		}
		"npc_petri_tower_of_evil"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1"	"scale"
		}
		"npc_petri_tower_of_evil_2"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.2"	"scale"
		}
		"npc_petri_tower_of_evil_3"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.4"	"scale"
		}
		"npc_petri_tower_of_evil_4"
		{
			"models/items/pugna/ward/draining_wight/draining_wight.vmdl" "model"
			"1.6"	"scale"
		}

		"npc_petri_tower_basic_death"
		{
			"models/creeps/item_creeps/i_creep_necro_archer/necro_archer.vmdl" "model"
		}
	}	
}	