GameRules.PETRI_TIME_LIMIT = 96
GameRules.PETRI_EXIT_MARK = 28
GameRules.PETRI_EXIT_ALLOWED = false
GameRules.PETRI_EXIT_WARNING = GameRules.PETRI_TIME_LIMIT - 12

GameRules.START_KVN_GOLD = 10
GameRules.START_KVN_LUMBER = 150

GameRules.START_PETROSYANS_GOLD = 33
GameRules.START_MINI_ACTORS_GOLD = 15

GameRules.PETRI_MAX_BUILDING_COUNT_PER_PLAYER = 27

GameRules.PETRI_MAX_WORKERS = 13
GameRules.PETRI_MAX_MEGA_WORKERS = 5

GameRules.EVASION_SCROLL_CHANCE = 98
GameRules.ATTACK_SCROLL_CHANCE = 94
GameRules.GOLD_COIN_CHANCE = 71
GameRules.WOOD_CHANCE = 53

GameRules.AUTO_GOLD_TIMINGS = {}
GameRules.AUTO_GOLD_TIMINGS[1] = 4
GameRules.AUTO_GOLD_TIMINGS[2] = 12
GameRules.AUTO_GOLD_TIMINGS[3] = 20
GameRules.AUTO_GOLD_TIMINGS[4] = 28
GameRules.AUTO_GOLD_TIMINGS[5] = 36

GameRules.PETRI_AUTO_GOLD = {}
GameRules.PETRI_AUTO_GOLD[1] = 1000
GameRules.PETRI_AUTO_GOLD[2] = 7500
GameRules.PETRI_AUTO_GOLD[3] = 20000
GameRules.PETRI_AUTO_GOLD[4] = 45000
GameRules.PETRI_AUTO_GOLD[5] = 125000

GameRules.KVN_AUTO_GOLD = {}
GameRules.KVN_AUTO_GOLD[1] = 190
GameRules.KVN_AUTO_GOLD[2] = 3200
GameRules.KVN_AUTO_GOLD[3] = 7200
GameRules.KVN_AUTO_GOLD[4] = 15435
GameRules.KVN_AUTO_GOLD[5] = 28435